theme: jekyll-theme-slate
title: PRL Workshop Series
descripion: While AI Planning and Reinforcement Learning communities focus on similar sequential decision-making problems, these communities remain somewhat unaware of each other on specific problems, techniques, methodologies, and evaluation. This workshop aims to encourage discussion and collaboration between the researchers in the fields of AI planning and reinforcement learning.
